name: Fedora 33 (head)

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'


env:
  YUM: dnf

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: fedora:33
    strategy:
      matrix:
        env:
          - SCRIPT: all_head

    env: ${{ matrix.env }}
    timeout-minutes: 70
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up build environment
        run: |
          ${{ env.YUM }} -y -q update
          ${{ env.YUM }} -y -q install --skip-broken \
            sudo \
            git \
            clang gcc gcc-c++ make autoconf automake libtool byacc bison \
            bzip2 gzip ncurses-devel bzip2-devel zlib-devel gettext-devel \
            patch \
            texinfo \
            file
      - name: Set up cacheable build environment
        run: |
          ci/install_prerequisites
      - name: Build GPG
        run: |
          bash -x "./examples/${SCRIPT}.sh"
